//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsdn.Janus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rsdn.Janus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} broken topic ({1}).
        /// </summary>
        internal static string BrokenTopicMessage1 {
            get {
                return ResourceManager.GetString("BrokenTopicMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} broken topics ({1}).
        /// </summary>
        internal static string BrokenTopicMessage2 {
            get {
                return ResourceManager.GetString("BrokenTopicMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} broken topics ({1}).
        /// </summary>
        internal static string BrokenTopicMessage5 {
            get {
                return ResourceManager.GetString("BrokenTopicMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent for message &apos;{0}&apos; not found.
        /// </summary>
        internal static string BrokenTopicRequestHint {
            get {
                return ResourceManager.GetString("BrokenTopicRequestHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken messages search.
        /// </summary>
        internal static string BrokenTopicRequestSource {
            get {
                return ResourceManager.GetString("BrokenTopicRequestSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use compression method &apos;{0}&apos;.
        /// </summary>
        internal static string CompressionUsed {
            get {
                return ResourceManager.GetString("CompressionUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download additional topics.
        /// </summary>
        internal static string DownloadTopics {
            get {
                return ResourceManager.GetString("DownloadTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} downloaded.
        /// </summary>
        internal static string DownloadTopicsStat {
            get {
                return ResourceManager.GetString("DownloadTopicsStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on deleting message with id=.
        /// </summary>
        internal static string ErrorOnMessageDelete {
            get {
                return ResourceManager.GetString("ErrorOnMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on processing message with id=.
        /// </summary>
        internal static string ErrorOnMessageProcessing {
            get {
                return ResourceManager.GetString("ErrorOnMessageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound message failed.
        /// </summary>
        internal static string FailedOutboundMessages1 {
            get {
                return ResourceManager.GetString("FailedOutboundMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound messages failed.
        /// </summary>
        internal static string FailedOutboundMessages2 {
            get {
                return ResourceManager.GetString("FailedOutboundMessages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound messages failed.
        /// </summary>
        internal static string FailedOutboundMessages5 {
            get {
                return ResourceManager.GetString("FailedOutboundMessages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forum.
        /// </summary>
        internal static string ForumsReceived1 {
            get {
                return ResourceManager.GetString("ForumsReceived1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forums.
        /// </summary>
        internal static string ForumsReceived2 {
            get {
                return ResourceManager.GetString("ForumsReceived2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forums.
        /// </summary>
        internal static string ForumsReceived5 {
            get {
                return ResourceManager.GetString("ForumsReceived5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query forums list from server.
        /// </summary>
        internal static string GetForumsList {
            get {
                return ResourceManager.GetString("GetForumsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound message.
        /// </summary>
        internal static string InboundMessages1 {
            get {
                return ResourceManager.GetString("InboundMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound messages.
        /// </summary>
        internal static string InboundMessages2 {
            get {
                return ResourceManager.GetString("InboundMessages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound messages.
        /// </summary>
        internal static string InboundMessages5 {
            get {
                return ResourceManager.GetString("InboundMessages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound rate.
        /// </summary>
        internal static string InboundRates1 {
            get {
                return ResourceManager.GetString("InboundRates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound rates.
        /// </summary>
        internal static string InboundRates2 {
            get {
                return ResourceManager.GetString("InboundRates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound rates.
        /// </summary>
        internal static string InboundRates5 {
            get {
                return ResourceManager.GetString("InboundRates5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexed.
        /// </summary>
        internal static string Indexed {
            get {
                return ResourceManager.GetString("Indexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string Messages1 {
            get {
                return ResourceManager.GetString("Messages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        internal static string Messages2 {
            get {
                return ResourceManager.GetString("Messages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        internal static string Messages5 {
            get {
                return ResourceManager.GetString("Messages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderatorial.
        /// </summary>
        internal static string Moderatorials1 {
            get {
                return ResourceManager.GetString("Moderatorials1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderatorials.
        /// </summary>
        internal static string Moderatorials2 {
            get {
                return ResourceManager.GetString("Moderatorials2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderatorials.
        /// </summary>
        internal static string Moderatorials5 {
            get {
                return ResourceManager.GetString("Moderatorials5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message processed.
        /// </summary>
        internal static string NewMsgProcessingProgressText1 {
            get {
                return ResourceManager.GetString("NewMsgProcessingProgressText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages processed.
        /// </summary>
        internal static string NewMsgProcessingProgressText2 {
            get {
                return ResourceManager.GetString("NewMsgProcessingProgressText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages processed.
        /// </summary>
        internal static string NewMsgProcessingProgressText5 {
            get {
                return ResourceManager.GetString("NewMsgProcessingProgressText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rate processed.
        /// </summary>
        internal static string NewRatesProcessingProgress1 {
            get {
                return ResourceManager.GetString("NewRatesProcessingProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rates processed.
        /// </summary>
        internal static string NewRatesProcessingProgress2 {
            get {
                return ResourceManager.GetString("NewRatesProcessingProgress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rates processed.
        /// </summary>
        internal static string NewRatesProcessingProgress5 {
            get {
                return ResourceManager.GetString("NewRatesProcessingProgress5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use no compression.
        /// </summary>
        internal static string NoCompression {
            get {
                return ResourceManager.GetString("NoCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound message.
        /// </summary>
        internal static string OutboundMessages1 {
            get {
                return ResourceManager.GetString("OutboundMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound messages.
        /// </summary>
        internal static string OutboundMessages2 {
            get {
                return ResourceManager.GetString("OutboundMessages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound messages.
        /// </summary>
        internal static string OutboundMessages5 {
            get {
                return ResourceManager.GetString("OutboundMessages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound rate.
        /// </summary>
        internal static string OutboundRates1 {
            get {
                return ResourceManager.GetString("OutboundRates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound rates.
        /// </summary>
        internal static string OutboundRates2 {
            get {
                return ResourceManager.GetString("OutboundRates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound rates.
        /// </summary>
        internal static string OutboundRates5 {
            get {
                return ResourceManager.GetString("OutboundRates5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post messages.
        /// </summary>
        internal static string PostMessages {
            get {
                return ResourceManager.GetString("PostMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing received messages.
        /// </summary>
        internal static string ProcessMessages {
            get {
                return ResourceManager.GetString("ProcessMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query new messages from forums.
        /// </summary>
        internal static string QueryNewMessages {
            get {
                return ResourceManager.GetString("QueryNewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query new user profiles from server.
        /// </summary>
        internal static string QueryNewUsers {
            get {
                return ResourceManager.GetString("QueryNewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query new violations.
        /// </summary>
        internal static string QueryNewViolations {
            get {
                return ResourceManager.GetString("QueryNewViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to forum(s)….
        /// </summary>
        internal static string SubscribeMessage {
            get {
                return ResourceManager.GetString("SubscribeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string UsersReceived1 {
            get {
                return ResourceManager.GetString("UsersReceived1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string UsersReceived2 {
            get {
                return ResourceManager.GetString("UsersReceived2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string UsersReceived5 {
            get {
                return ResourceManager.GetString("UsersReceived5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete forum &apos;{0}&apos; records?.
        /// </summary>
        internal static string WarningOnUnsubscribeForum {
            get {
                return ResourceManager.GetString("WarningOnUnsubscribeForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string WarningOnUnsubscribeForumCaption {
            get {
                return ResourceManager.GetString("WarningOnUnsubscribeForumCaption", resourceCulture);
            }
        }
    }
}
