//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsdn.PropGridCust
{
    
    
    internal partial class SR
    {
        
        public static System.Resources.ResourceManager _resourceManager = null;
        
        public const string BooleanFalseResourceName = "BooleanFalse";
        
        public const string BooleanTrueResourceName = "BooleanTrue";
        
        public const string CollectionNameResourceName = "CollectionName";
        
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                return _resourceManager;
            }
            set
            {
                _resourceManager = value;
            }
        }
        
        public static string BooleanFalse
        {
            get
            {
                return SR.ResourceManager.GetString(BooleanFalseResourceName);
            }
        }
        
        public static string BooleanTrue
        {
            get
            {
                return SR.ResourceManager.GetString(BooleanTrueResourceName);
            }
        }
        
        public static string CollectionName
        {
            get
            {
                return SR.ResourceManager.GetString(CollectionNameResourceName);
            }
        }
    }
}
