//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30128.1
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsdn.Janus.Jet {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rsdn.Janus.Jet.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Compact DB.
		/// </summary>
		internal static string CompactDb {
			get {
				return ResourceManager.GetString("CompactDb", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Database packing in progress.
		/// </summary>
		internal static string CompactDbProgressText {
			get {
				return ResourceManager.GetString("CompactDbProgressText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Database path:.
		/// </summary>
		internal static string DatabasePath {
			get {
				return ResourceManager.GetString("DatabasePath", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to JET Engine Driver (Access database).
		/// </summary>
		internal static string DriverDescription {
			get {
				return ResourceManager.GetString("DriverDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to JET.
		/// </summary>
		internal static string DriverDisplayName {
			get {
				return ResourceManager.GetString("DriverDisplayName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to JET Support.
		/// </summary>
		internal static string ExtensionDisplayName {
			get {
				return ResourceManager.GetString("ExtensionDisplayName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Access files (*.mdb)|*.mdb|All files (*.*)|*.*.
		/// </summary>
		internal static string OpenFileDialogFilter {
			get {
				return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
			}
		}
	}
}
