//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30128.1
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsdn.Janus.Core.TextMacros.SimpleMacros {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class SimpleMacrosResources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SimpleMacrosResources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rsdn.Janus.Core.TextMacros.SimpleMacros.SimpleMacrosResources", typeof(SimpleMacrosResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Application Copyright.
		/// </summary>
		internal static string ApplicationCopyright {
			get {
				return ResourceManager.GetString("ApplicationCopyright", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Application Name.
		/// </summary>
		internal static string ApplicationName {
			get {
				return ResourceManager.GetString("ApplicationName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Application Release.
		/// </summary>
		internal static string ApplicationRelease {
			get {
				return ResourceManager.GetString("ApplicationRelease", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Application Revision.
		/// </summary>
		internal static string ApplicationRevision {
			get {
				return ResourceManager.GetString("ApplicationRevision", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Application Version.
		/// </summary>
		internal static string ApplicationVersion {
			get {
				return ResourceManager.GetString("ApplicationVersion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Framework Version.
		/// </summary>
		internal static string FrameworkVersion {
			get {
				return ResourceManager.GetString("FrameworkVersion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Your Nick.
		/// </summary>
		internal static string Nick {
			get {
				return ResourceManager.GetString("Nick", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to OS Name.
		/// </summary>
		internal static string OSName {
			get {
				return ResourceManager.GetString("OSName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to OS Version.
		/// </summary>
		internal static string OSVersion {
			get {
				return ResourceManager.GetString("OSVersion", resourceCulture);
			}
		}
	}
}
