//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsdn.Janus.Core.Synchronization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyncResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rsdn.Janus.Core.Synchronization.SyncResources", typeof(SyncResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization on proxy ({0}) complete.
        /// </summary>
        internal static string AuthOnProxyIsComplete {
            get {
                return ResourceManager.GetString("AuthOnProxyIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization on proxy ({0}) failed.
        /// </summary>
        internal static string AuthOnProxyIsFailed {
            get {
                return ResourceManager.GetString("AuthOnProxyIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization on proxy {0}.
        /// </summary>
        internal static string ProxyAuthOn {
            get {
                return ResourceManager.GetString("ProxyAuthOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy authorization required (407).
        /// </summary>
        internal static string ProxyDemandAuth {
            get {
                return ResourceManager.GetString("ProxyDemandAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct connection.
        /// </summary>
        internal static string ProxyDirectConnection {
            get {
                return ResourceManager.GetString("ProxyDirectConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization decline by user .
        /// </summary>
        internal static string ProxyUserDeclineAuth {
            get {
                return ResourceManager.GetString("ProxyUserDeclineAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization alerady active..
        /// </summary>
        internal static string SyncAlreadyActive {
            get {
                return ResourceManager.GetString("SyncAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization error: {0}.
        /// </summary>
        internal static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization warning: {0}.
        /// </summary>
        internal static string SyncWarning {
            get {
                return ResourceManager.GetString("SyncWarning", resourceCulture);
            }
        }
    }
}
