//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:2.0.50727.1433
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peak.TreeGrid.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peak.TreeGrid.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to AlternateRow.
		/// </summary>
		internal static string Alternate {
			get {
				return ResourceManager.GetString("Alternate", resourceCulture);
			}
		}
		
		internal static System.Drawing.Bitmap Collapse {
			get {
				object obj = ResourceManager.GetObject("Collapse", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ControlActive.
		/// </summary>
		internal static string ControlActive {
			get {
				return ResourceManager.GetString("ControlActive", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ControlEnabled.
		/// </summary>
		internal static string ControlEnabled {
			get {
				return ResourceManager.GetString("ControlEnabled", resourceCulture);
			}
		}
		
		internal static System.Drawing.Bitmap Expand {
			get {
				object obj = ResourceManager.GetObject("Expand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ItemFocused.
		/// </summary>
		internal static string Focused {
			get {
				return ResourceManager.GetString("Focused", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ItemSelected.
		/// </summary>
		internal static string Selected {
			get {
				return ResourceManager.GetString("Selected", resourceCulture);
			}
		}
	}
}
