//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30128.1
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsdn.Janus.Core.NotifyIcon {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class NotifyIconResources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal NotifyIconResources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rsdn.Janus.Core.NotifyIcon.NotifyIconResources", typeof(NotifyIconResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to unread answer.
		/// </summary>
		internal static string HintMeMessages1 {
			get {
				return ResourceManager.GetString("HintMeMessages1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to unread answers.
		/// </summary>
		internal static string HintMeMessages2 {
			get {
				return ResourceManager.GetString("HintMeMessages2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to unread answers.
		/// </summary>
		internal static string HintMeMessages5 {
			get {
				return ResourceManager.GetString("HintMeMessages5", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to new message.
		/// </summary>
		internal static string HintNewMessages1 {
			get {
				return ResourceManager.GetString("HintNewMessages1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to new messages.
		/// </summary>
		internal static string HintNewMessages2 {
			get {
				return ResourceManager.GetString("HintNewMessages2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to new messages.
		/// </summary>
		internal static string HintNewMessages5 {
			get {
				return ResourceManager.GetString("HintNewMessages5", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to unread message.
		/// </summary>
		internal static string HintUnreadMessages1 {
			get {
				return ResourceManager.GetString("HintUnreadMessages1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to unread messages.
		/// </summary>
		internal static string HintUnreadMessages2 {
			get {
				return ResourceManager.GetString("HintUnreadMessages2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to unread messages.
		/// </summary>
		internal static string HintUnreadMessages5 {
			get {
				return ResourceManager.GetString("HintUnreadMessages5", resourceCulture);
			}
		}
	}
}
