//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Rsdn.Janus.org.rsdn {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JanusATSoap", Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusAT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTopicByMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetForumListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByIdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostChangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostChangeCommitOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewViolationsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JanusAT() {
            this.Url = global::Rsdn.Janus.Properties.Settings.Default.Janus_Rsdn_org_rsdn_JanusAT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTopicByMessageCompletedEventHandler GetTopicByMessageCompleted;
        
        /// <remarks/>
        public event GetNewDataCompletedEventHandler GetNewDataCompleted;
        
        /// <remarks/>
        public event GetForumListCompletedEventHandler GetForumListCompleted;
        
        /// <remarks/>
        public event GetNewUsersCompletedEventHandler GetNewUsersCompleted;
        
        /// <remarks/>
        public event GetUserByIdsCompletedEventHandler GetUserByIdsCompleted;
        
        /// <remarks/>
        public event PostChangeCompletedEventHandler PostChangeCompleted;
        
        /// <remarks/>
        public event PostChangeCommitCompletedEventHandler PostChangeCommitCompleted;
        
        /// <remarks/>
        public event CheckCompletedEventHandler CheckCompleted;
        
        /// <remarks/>
        public event GetNewViolationsCompletedEventHandler GetNewViolationsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/GetTopicByMessage", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TopicResponse GetTopicByMessage(TopicRequest topicRequest) {
            object[] results = this.Invoke("GetTopicByMessage", new object[] {
                        topicRequest});
            return ((TopicResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopicByMessageAsync(TopicRequest topicRequest) {
            this.GetTopicByMessageAsync(topicRequest, null);
        }
        
        /// <remarks/>
        public void GetTopicByMessageAsync(TopicRequest topicRequest, object userState) {
            if ((this.GetTopicByMessageOperationCompleted == null)) {
                this.GetTopicByMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopicByMessageOperationCompleted);
            }
            this.InvokeAsync("GetTopicByMessage", new object[] {
                        topicRequest}, this.GetTopicByMessageOperationCompleted, userState);
        }
        
        private void OnGetTopicByMessageOperationCompleted(object arg) {
            if ((this.GetTopicByMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopicByMessageCompleted(this, new GetTopicByMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/GetNewData", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChangeResponse GetNewData(ChangeRequest changeRequest) {
            object[] results = this.Invoke("GetNewData", new object[] {
                        changeRequest});
            return ((ChangeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewDataAsync(ChangeRequest changeRequest) {
            this.GetNewDataAsync(changeRequest, null);
        }
        
        /// <remarks/>
        public void GetNewDataAsync(ChangeRequest changeRequest, object userState) {
            if ((this.GetNewDataOperationCompleted == null)) {
                this.GetNewDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewDataOperationCompleted);
            }
            this.InvokeAsync("GetNewData", new object[] {
                        changeRequest}, this.GetNewDataOperationCompleted, userState);
        }
        
        private void OnGetNewDataOperationCompleted(object arg) {
            if ((this.GetNewDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewDataCompleted(this, new GetNewDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/GetForumList", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ForumResponse GetForumList(ForumRequest forumRequest) {
            object[] results = this.Invoke("GetForumList", new object[] {
                        forumRequest});
            return ((ForumResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetForumListAsync(ForumRequest forumRequest) {
            this.GetForumListAsync(forumRequest, null);
        }
        
        /// <remarks/>
        public void GetForumListAsync(ForumRequest forumRequest, object userState) {
            if ((this.GetForumListOperationCompleted == null)) {
                this.GetForumListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetForumListOperationCompleted);
            }
            this.InvokeAsync("GetForumList", new object[] {
                        forumRequest}, this.GetForumListOperationCompleted, userState);
        }
        
        private void OnGetForumListOperationCompleted(object arg) {
            if ((this.GetForumListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetForumListCompleted(this, new GetForumListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/GetNewUsers", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserResponse GetNewUsers(UserRequest userRequest) {
            object[] results = this.Invoke("GetNewUsers", new object[] {
                        userRequest});
            return ((UserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewUsersAsync(UserRequest userRequest) {
            this.GetNewUsersAsync(userRequest, null);
        }
        
        /// <remarks/>
        public void GetNewUsersAsync(UserRequest userRequest, object userState) {
            if ((this.GetNewUsersOperationCompleted == null)) {
                this.GetNewUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewUsersOperationCompleted);
            }
            this.InvokeAsync("GetNewUsers", new object[] {
                        userRequest}, this.GetNewUsersOperationCompleted, userState);
        }
        
        private void OnGetNewUsersOperationCompleted(object arg) {
            if ((this.GetNewUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewUsersCompleted(this, new GetNewUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/GetUserByIds", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserResponse GetUserByIds(UserByIdsRequest request) {
            object[] results = this.Invoke("GetUserByIds", new object[] {
                        request});
            return ((UserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByIdsAsync(UserByIdsRequest request) {
            this.GetUserByIdsAsync(request, null);
        }
        
        /// <remarks/>
        public void GetUserByIdsAsync(UserByIdsRequest request, object userState) {
            if ((this.GetUserByIdsOperationCompleted == null)) {
                this.GetUserByIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByIdsOperationCompleted);
            }
            this.InvokeAsync("GetUserByIds", new object[] {
                        request}, this.GetUserByIdsOperationCompleted, userState);
        }
        
        private void OnGetUserByIdsOperationCompleted(object arg) {
            if ((this.GetUserByIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByIdsCompleted(this, new GetUserByIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/PostChange", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostChange(PostRequest postRequest) {
            this.Invoke("PostChange", new object[] {
                        postRequest});
        }
        
        /// <remarks/>
        public void PostChangeAsync(PostRequest postRequest) {
            this.PostChangeAsync(postRequest, null);
        }
        
        /// <remarks/>
        public void PostChangeAsync(PostRequest postRequest, object userState) {
            if ((this.PostChangeOperationCompleted == null)) {
                this.PostChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostChangeOperationCompleted);
            }
            this.InvokeAsync("PostChange", new object[] {
                        postRequest}, this.PostChangeOperationCompleted, userState);
        }
        
        private void OnPostChangeOperationCompleted(object arg) {
            if ((this.PostChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostChangeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/PostChangeCommit", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PostResponse PostChangeCommit() {
            object[] results = this.Invoke("PostChangeCommit", new object[0]);
            return ((PostResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PostChangeCommitAsync() {
            this.PostChangeCommitAsync(null);
        }
        
        /// <remarks/>
        public void PostChangeCommitAsync(object userState) {
            if ((this.PostChangeCommitOperationCompleted == null)) {
                this.PostChangeCommitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostChangeCommitOperationCompleted);
            }
            this.InvokeAsync("PostChangeCommit", new object[0], this.PostChangeCommitOperationCompleted, userState);
        }
        
        private void OnPostChangeCommitOperationCompleted(object arg) {
            if ((this.PostChangeCommitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostChangeCommitCompleted(this, new PostChangeCommitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/Check", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Check() {
            this.Invoke("Check", new object[0]);
        }
        
        /// <remarks/>
        public void CheckAsync() {
            this.CheckAsync(null);
        }
        
        /// <remarks/>
        public void CheckAsync(object userState) {
            if ((this.CheckOperationCompleted == null)) {
                this.CheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOperationCompleted);
            }
            this.InvokeAsync("Check", new object[0], this.CheckOperationCompleted, userState);
        }
        
        private void OnCheckOperationCompleted(object arg) {
            if ((this.CheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rsdn.ru/Janus/GetNewViolations", RequestNamespace="http://rsdn.ru/Janus/", ResponseNamespace="http://rsdn.ru/Janus/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ViolationResponse GetNewViolations(ViolationRequest request) {
            object[] results = this.Invoke("GetNewViolations", new object[] {
                        request});
            return ((ViolationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewViolationsAsync(ViolationRequest request) {
            this.GetNewViolationsAsync(request, null);
        }
        
        /// <remarks/>
        public void GetNewViolationsAsync(ViolationRequest request, object userState) {
            if ((this.GetNewViolationsOperationCompleted == null)) {
                this.GetNewViolationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewViolationsOperationCompleted);
            }
            this.InvokeAsync("GetNewViolations", new object[] {
                        request}, this.GetNewViolationsOperationCompleted, userState);
        }
        
        private void OnGetNewViolationsOperationCompleted(object arg) {
            if ((this.GetNewViolationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewViolationsCompleted(this, new GetNewViolationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class TopicRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private int[] messageIdsField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int[] messageIds {
            get {
                return this.messageIdsField;
            }
            set {
                this.messageIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusViolationInfo {
        
        private int messageIDField;
        
        private string reasonField;
        
        private System.DateTime createdOnField;
        
        private PenaltyType penaltyTypeField;
        
        private byte[] rowVersionField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        public PenaltyType PenaltyType {
            get {
                return this.penaltyTypeField;
            }
            set {
                this.penaltyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RowVersion {
            get {
                return this.rowVersionField;
            }
            set {
                this.rowVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public enum PenaltyType {
        
        /// <remarks/>
        Ban,
        
        /// <remarks/>
        Close,
        
        /// <remarks/>
        Warning,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class ViolationResponse {
        
        private JanusViolationInfo[] violationsField;
        
        /// <remarks/>
        public JanusViolationInfo[] Violations {
            get {
                return this.violationsField;
            }
            set {
                this.violationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class ViolationRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private RequestForumInfo[] subscribedForumsField;
        
        private byte[] lastRowVersionField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public RequestForumInfo[] SubscribedForums {
            get {
                return this.subscribedForumsField;
            }
            set {
                this.subscribedForumsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] LastRowVersion {
            get {
                return this.lastRowVersionField;
            }
            set {
                this.lastRowVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class RequestForumInfo {
        
        private int forumIdField;
        
        private bool isFirstRequestField;
        
        /// <remarks/>
        public int forumId {
            get {
                return this.forumIdField;
            }
            set {
                this.forumIdField = value;
            }
        }
        
        /// <remarks/>
        public bool isFirstRequest {
            get {
                return this.isFirstRequestField;
            }
            set {
                this.isFirstRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class ModerateExceptionInfo {
        
        private string exceptionMessageField;
        
        private int localModerateIdField;
        
        private string infoField;
        
        /// <remarks/>
        public string ExceptionMessage {
            get {
                return this.exceptionMessageField;
            }
            set {
                this.exceptionMessageField = value;
            }
        }
        
        /// <remarks/>
        public int LocalModerateId {
            get {
                return this.localModerateIdField;
            }
            set {
                this.localModerateIdField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class RatingExceptionInfo {
        
        private string exceptionField;
        
        private int localRatingIdField;
        
        private string infoField;
        
        /// <remarks/>
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        public int localRatingId {
            get {
                return this.localRatingIdField;
            }
            set {
                this.localRatingIdField = value;
            }
        }
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class PostExceptionInfo {
        
        private string exceptionField;
        
        private int localMessageIdField;
        
        private string infoField;
        
        /// <remarks/>
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        public int localMessageId {
            get {
                return this.localMessageIdField;
            }
            set {
                this.localMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class PostResponse {
        
        private int[] commitedIdsField;
        
        private PostExceptionInfo[] exceptionsField;
        
        private int[] commitedRatingIdsField;
        
        private RatingExceptionInfo[] ratingExceptionsField;
        
        private int[] commitedModerateIdsField;
        
        private ModerateExceptionInfo[] moderateExceptionsField;
        
        /// <remarks/>
        public int[] commitedIds {
            get {
                return this.commitedIdsField;
            }
            set {
                this.commitedIdsField = value;
            }
        }
        
        /// <remarks/>
        public PostExceptionInfo[] exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
        
        /// <remarks/>
        public int[] commitedRatingIds {
            get {
                return this.commitedRatingIdsField;
            }
            set {
                this.commitedRatingIdsField = value;
            }
        }
        
        /// <remarks/>
        public RatingExceptionInfo[] ratingExceptions {
            get {
                return this.ratingExceptionsField;
            }
            set {
                this.ratingExceptionsField = value;
            }
        }
        
        /// <remarks/>
        public int[] commitedModerateIds {
            get {
                return this.commitedModerateIdsField;
            }
            set {
                this.commitedModerateIdsField = value;
            }
        }
        
        /// <remarks/>
        public ModerateExceptionInfo[] moderateExceptions {
            get {
                return this.moderateExceptionsField;
            }
            set {
                this.moderateExceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class PostModerateInfo {
        
        private int localModerateIdField;
        
        private int messageIdField;
        
        private ModerateActionType moderateActionField;
        
        private int moderateToForumIdField;
        
        private string descriptionField;
        
        private bool asModeratorField;
        
        /// <remarks/>
        public int LocalModerateId {
            get {
                return this.localModerateIdField;
            }
            set {
                this.localModerateIdField = value;
            }
        }
        
        /// <remarks/>
        public int MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public ModerateActionType ModerateAction {
            get {
                return this.moderateActionField;
            }
            set {
                this.moderateActionField = value;
            }
        }
        
        /// <remarks/>
        public int ModerateToForumId {
            get {
                return this.moderateToForumIdField;
            }
            set {
                this.moderateToForumIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool AsModerator {
            get {
                return this.asModeratorField;
            }
            set {
                this.asModeratorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public enum ModerateActionType {
        
        /// <remarks/>
        MoveMessage,
        
        /// <remarks/>
        DeleteMessage,
        
        /// <remarks/>
        DeleteThread,
        
        /// <remarks/>
        DeleteErrorMessage,
        
        /// <remarks/>
        SplitThread,
        
        /// <remarks/>
        CloseTopic,
        
        /// <remarks/>
        OpenTopic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class PostRatingInfo {
        
        private int localRatingIdField;
        
        private int messageIdField;
        
        private int rateField;
        
        /// <remarks/>
        public int localRatingId {
            get {
                return this.localRatingIdField;
            }
            set {
                this.localRatingIdField = value;
            }
        }
        
        /// <remarks/>
        public int messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public int rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class PostMessageInfo {
        
        private int localMessageIdField;
        
        private int parentIdField;
        
        private int forumIdField;
        
        private string subjectField;
        
        private string messageField;
        
        private string tagsField;
        
        /// <remarks/>
        public int localMessageId {
            get {
                return this.localMessageIdField;
            }
            set {
                this.localMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public int parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public int forumId {
            get {
                return this.forumIdField;
            }
            set {
                this.forumIdField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class PostRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private PostMessageInfo[] writedMessagesField;
        
        private PostRatingInfo[] ratesField;
        
        private PostModerateInfo[] moderatesField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public PostMessageInfo[] writedMessages {
            get {
                return this.writedMessagesField;
            }
            set {
                this.writedMessagesField = value;
            }
        }
        
        /// <remarks/>
        public PostRatingInfo[] rates {
            get {
                return this.ratesField;
            }
            set {
                this.ratesField = value;
            }
        }
        
        /// <remarks/>
        public PostModerateInfo[] moderates {
            get {
                return this.moderatesField;
            }
            set {
                this.moderatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class UserByIdsRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private int[] userIdsField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int[] userIds {
            get {
                return this.userIdsField;
            }
            set {
                this.userIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusUserInfo {
        
        private int userIdField;
        
        private string userNameField;
        
        private string userNickField;
        
        private string realNameField;
        
        private string publicEmailField;
        
        private string homePageField;
        
        private string specializationField;
        
        private string whereFromField;
        
        private string originField;
        
        private int userClassField;
        
        private string gravatarHashField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string userNick {
            get {
                return this.userNickField;
            }
            set {
                this.userNickField = value;
            }
        }
        
        /// <remarks/>
        public string realName {
            get {
                return this.realNameField;
            }
            set {
                this.realNameField = value;
            }
        }
        
        /// <remarks/>
        public string publicEmail {
            get {
                return this.publicEmailField;
            }
            set {
                this.publicEmailField = value;
            }
        }
        
        /// <remarks/>
        public string homePage {
            get {
                return this.homePageField;
            }
            set {
                this.homePageField = value;
            }
        }
        
        /// <remarks/>
        public string specialization {
            get {
                return this.specializationField;
            }
            set {
                this.specializationField = value;
            }
        }
        
        /// <remarks/>
        public string whereFrom {
            get {
                return this.whereFromField;
            }
            set {
                this.whereFromField = value;
            }
        }
        
        /// <remarks/>
        public string origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public int userClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public string gravatarHash {
            get {
                return this.gravatarHashField;
            }
            set {
                this.gravatarHashField = value;
            }
        }
        
        /// <remarks/>
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class UserResponse {
        
        private byte[] lastRowVersionField;
        
        private JanusUserInfo[] usersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] lastRowVersion {
            get {
                return this.lastRowVersionField;
            }
            set {
                this.lastRowVersionField = value;
            }
        }
        
        /// <remarks/>
        public JanusUserInfo[] users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class UserRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private byte[] lastRowVersionField;
        
        private int maxOutputField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] lastRowVersion {
            get {
                return this.lastRowVersionField;
            }
            set {
                this.lastRowVersionField = value;
            }
        }
        
        /// <remarks/>
        public int maxOutput {
            get {
                return this.maxOutputField;
            }
            set {
                this.maxOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusForumGroupInfo {
        
        private int forumGroupIdField;
        
        private string forumGroupNameField;
        
        private int sortOrderField;
        
        /// <remarks/>
        public int forumGroupId {
            get {
                return this.forumGroupIdField;
            }
            set {
                this.forumGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string forumGroupName {
            get {
                return this.forumGroupNameField;
            }
            set {
                this.forumGroupNameField = value;
            }
        }
        
        /// <remarks/>
        public int sortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusForumInfo {
        
        private int forumIdField;
        
        private int forumGroupIdField;
        
        private string shortForumNameField;
        
        private string forumNameField;
        
        private int ratedField;
        
        private int inTopField;
        
        private int rateLimitField;
        
        /// <remarks/>
        public int forumId {
            get {
                return this.forumIdField;
            }
            set {
                this.forumIdField = value;
            }
        }
        
        /// <remarks/>
        public int forumGroupId {
            get {
                return this.forumGroupIdField;
            }
            set {
                this.forumGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string shortForumName {
            get {
                return this.shortForumNameField;
            }
            set {
                this.shortForumNameField = value;
            }
        }
        
        /// <remarks/>
        public string forumName {
            get {
                return this.forumNameField;
            }
            set {
                this.forumNameField = value;
            }
        }
        
        /// <remarks/>
        public int rated {
            get {
                return this.ratedField;
            }
            set {
                this.ratedField = value;
            }
        }
        
        /// <remarks/>
        public int inTop {
            get {
                return this.inTopField;
            }
            set {
                this.inTopField = value;
            }
        }
        
        /// <remarks/>
        public int rateLimit {
            get {
                return this.rateLimitField;
            }
            set {
                this.rateLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class ForumResponse {
        
        private JanusForumInfo[] forumListField;
        
        private JanusForumGroupInfo[] groupListField;
        
        private byte[] forumsRowVersionField;
        
        /// <remarks/>
        public JanusForumInfo[] forumList {
            get {
                return this.forumListField;
            }
            set {
                this.forumListField = value;
            }
        }
        
        /// <remarks/>
        public JanusForumGroupInfo[] groupList {
            get {
                return this.groupListField;
            }
            set {
                this.groupListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] forumsRowVersion {
            get {
                return this.forumsRowVersionField;
            }
            set {
                this.forumsRowVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class ForumRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private byte[] forumsRowVersionField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] forumsRowVersion {
            get {
                return this.forumsRowVersionField;
            }
            set {
                this.forumsRowVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class ChangeResponse {
        
        private JanusMessageInfo[] newMessagesField;
        
        private JanusRatingInfo[] newRatingField;
        
        private JanusModerateInfo[] newModerateField;
        
        private byte[] lastRatingRowVersionField;
        
        private byte[] lastForumRowVersionField;
        
        private byte[] lastModerateRowVersionField;
        
        private int userIdField;
        
        /// <remarks/>
        public JanusMessageInfo[] newMessages {
            get {
                return this.newMessagesField;
            }
            set {
                this.newMessagesField = value;
            }
        }
        
        /// <remarks/>
        public JanusRatingInfo[] newRating {
            get {
                return this.newRatingField;
            }
            set {
                this.newRatingField = value;
            }
        }
        
        /// <remarks/>
        public JanusModerateInfo[] newModerate {
            get {
                return this.newModerateField;
            }
            set {
                this.newModerateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] lastRatingRowVersion {
            get {
                return this.lastRatingRowVersionField;
            }
            set {
                this.lastRatingRowVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] lastForumRowVersion {
            get {
                return this.lastForumRowVersionField;
            }
            set {
                this.lastForumRowVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] lastModerateRowVersion {
            get {
                return this.lastModerateRowVersionField;
            }
            set {
                this.lastModerateRowVersionField = value;
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusMessageInfo {
        
        private int messageIdField;
        
        private int topicIdField;
        
        private int parentIdField;
        
        private int userIdField;
        
        private int forumIdField;
        
        private string subjectField;
        
        private string messageNameField;
        
        private string userNickField;
        
        private string messageField;
        
        private int articleIdField;
        
        private System.DateTime messageDateField;
        
        private System.DateTime updateDateField;
        
        private UserRole userRoleField;
        
        private string userTitleField;
        
        private int userTitleColorField;
        
        private System.DateTime lastModeratedField;
        
        private bool closedField;
        
        private string[] tagsField;
        
        /// <remarks/>
        public int messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public int topicId {
            get {
                return this.topicIdField;
            }
            set {
                this.topicIdField = value;
            }
        }
        
        /// <remarks/>
        public int parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int forumId {
            get {
                return this.forumIdField;
            }
            set {
                this.forumIdField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string messageName {
            get {
                return this.messageNameField;
            }
            set {
                this.messageNameField = value;
            }
        }
        
        /// <remarks/>
        public string userNick {
            get {
                return this.userNickField;
            }
            set {
                this.userNickField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int articleId {
            get {
                return this.articleIdField;
            }
            set {
                this.articleIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime messageDate {
            get {
                return this.messageDateField;
            }
            set {
                this.messageDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        public UserRole userRole {
            get {
                return this.userRoleField;
            }
            set {
                this.userRoleField = value;
            }
        }
        
        /// <remarks/>
        public string userTitle {
            get {
                return this.userTitleField;
            }
            set {
                this.userTitleField = value;
            }
        }
        
        /// <remarks/>
        public int userTitleColor {
            get {
                return this.userTitleColorField;
            }
            set {
                this.userTitleColorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastModerated {
            get {
                return this.lastModeratedField;
            }
            set {
                this.lastModeratedField = value;
            }
        }
        
        /// <remarks/>
        public bool closed {
            get {
                return this.closedField;
            }
            set {
                this.closedField = value;
            }
        }
        
        /// <remarks/>
        public string[] tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public enum UserRole {
        
        /// <remarks/>
        Admin,
        
        /// <remarks/>
        Moderator,
        
        /// <remarks/>
        TeamMember,
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Expert,
        
        /// <remarks/>
        Anonym,
        
        /// <remarks/>
        Group,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusRatingInfo {
        
        private int messageIdField;
        
        private int topicIdField;
        
        private int userIdField;
        
        private int userRatingField;
        
        private int rateField;
        
        private System.DateTime rateDateField;
        
        /// <remarks/>
        public int messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public int topicId {
            get {
                return this.topicIdField;
            }
            set {
                this.topicIdField = value;
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int userRating {
            get {
                return this.userRatingField;
            }
            set {
                this.userRatingField = value;
            }
        }
        
        /// <remarks/>
        public int rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime rateDate {
            get {
                return this.rateDateField;
            }
            set {
                this.rateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class JanusModerateInfo {
        
        private int messageIdField;
        
        private int topicIdField;
        
        private int userIdField;
        
        private int forumIdField;
        
        private System.DateTime createField;
        
        /// <remarks/>
        public int messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public int topicId {
            get {
                return this.topicIdField;
            }
            set {
                this.topicIdField = value;
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int forumId {
            get {
                return this.forumIdField;
            }
            set {
                this.forumIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class ChangeRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private RequestForumInfo[] subscribedForumsField;
        
        private byte[] ratingRowVersionField;
        
        private byte[] messageRowVersionField;
        
        private byte[] moderateRowVersionField;
        
        private int[] breakMsgIdsField;
        
        private int[] breakTopicIdsField;
        
        private int maxOutputField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public RequestForumInfo[] subscribedForums {
            get {
                return this.subscribedForumsField;
            }
            set {
                this.subscribedForumsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ratingRowVersion {
            get {
                return this.ratingRowVersionField;
            }
            set {
                this.ratingRowVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] messageRowVersion {
            get {
                return this.messageRowVersionField;
            }
            set {
                this.messageRowVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] moderateRowVersion {
            get {
                return this.moderateRowVersionField;
            }
            set {
                this.moderateRowVersionField = value;
            }
        }
        
        /// <remarks/>
        public int[] breakMsgIds {
            get {
                return this.breakMsgIdsField;
            }
            set {
                this.breakMsgIdsField = value;
            }
        }
        
        /// <remarks/>
        public int[] breakTopicIds {
            get {
                return this.breakTopicIdsField;
            }
            set {
                this.breakTopicIdsField = value;
            }
        }
        
        /// <remarks/>
        public int maxOutput {
            get {
                return this.maxOutputField;
            }
            set {
                this.maxOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.2012.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsdn.ru/Janus/")]
    public partial class TopicResponse {
        
        private JanusMessageInfo[] messagesField;
        
        private JanusRatingInfo[] ratingField;
        
        private JanusModerateInfo[] moderateField;
        
        /// <remarks/>
        public JanusMessageInfo[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public JanusRatingInfo[] Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        public JanusModerateInfo[] Moderate {
            get {
                return this.moderateField;
            }
            set {
                this.moderateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void GetTopicByMessageCompletedEventHandler(object sender, GetTopicByMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopicByMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopicByMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TopicResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TopicResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void GetNewDataCompletedEventHandler(object sender, GetNewDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChangeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChangeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void GetForumListCompletedEventHandler(object sender, GetForumListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetForumListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetForumListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ForumResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ForumResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void GetNewUsersCompletedEventHandler(object sender, GetNewUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void GetUserByIdsCompletedEventHandler(object sender, GetUserByIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void PostChangeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void PostChangeCommitCompletedEventHandler(object sender, PostChangeCommitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostChangeCommitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostChangeCommitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void CheckCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void GetNewViolationsCompletedEventHandler(object sender, GetNewViolationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewViolationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewViolationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViolationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViolationResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591